#!/bin/bash

if [ $1 = "--help" ]; then
  echo "usage: ./push --file <filename>"
elif [ $1 = "--file" ]; then
  filename=$2
  while read line
  do
    echo "$line"
    date +"%Y-%m-%d %H:%M:%S" | tr -d "\n" >> "$filename"; printf "," >> "$filename"; echo "$line" >> "$filename";  
  done < /dev/stdin
fi
